---

- include_tasks: ppa.yml

- include_tasks: repositories.yml

- include_tasks: install.yml

- include_tasks: snap.yml

- include_tasks: flatpak.yml

- include_tasks: pipx.yml

- include_tasks: remove.yml
